### ISSUE TITLE
How to increase DLL limit?

### ISSUE THREAD

**Issue by ozgeevrim82** [hbc/bcbioSingleCell#66]
Hi,
I have this error: `maximal number of DLLs reached...' I see in the troubleshooting section here that I can increase DLL limit by:
Append this line to your ~/.Renviron file:
R_MAX_NUM_DLLS=150

I couldn't figure out how to do it. May I get help?
Thanks!

**Comment by mjsteinbaugh** [comment]
Hi @ozgeevrim82, great question. What operating system are you using?

If you're using Mac or Linux, simply open the Terminal (bash), and run:

```bash
# Alternatively, can use vim instead of nano
nano ~/.Renviron
```

In the editor, save this line:

```
R_MAX_NUM_DLLS=150
```

For nano, just hit <kbd>Ctrl</kbd> + <kbd>X</kbd> to quit and save. 

You can see how many DLLs are loaded with `getLoadedDLLs()` in R, which will start to add up when analyzing single-cell data, since there are a lot of dependencies.

Here's some more detailed information from the R documentation:
https://www.rdocumentation.org/packages/base/versions/3.5.0/topics/dyn.load

**Comment by ozgeevrim82** [comment]
Hi mjsteinbaugh,
Thank you for the helpful comments! Unfortunately I couldn't locate the .Renviron file to edit. I am curious how can I find its path? When I run getLoadedDLLs() in R studio, I get the list of libraries. Here I copy pasted a few of them as an example:
methods                /Library/Frameworks/R.framework/Versions/3.4/Resources/library/methods/libs/methods.so
utils                      /Library/Frameworks/R.framework/Versions/3.4/Resources/library/utils/libs/utils.so
grDevices          /Library/Frameworks/R.framework/Versions/3.4/Resources/library/grDevices/libs/grDevices.so

I looked for '/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  or folders above, but couldn't locate the file. May you give any ideas for how to find it?
Thanks in advance!

**Comment by mjsteinbaugh** [comment]
Right, so the `.Renviron` file is an invisible file that gets saved in your user directory. Since you appear to be using the Mac, this will be at `/Users/XXX/.Renviron`, or `~/.Renviron` in the Terminal. This file is invisible in the Finder but you can see it in the Terminal using `ls -al`. If you want to save this with a text editor, I recommend BBEdit, which allows for editing of invisible files.
